### ISSUE TITLE
Crash + Android Whitelist doesn't work + Config option requests

### ISSUE THREAD

**Issue by brandyyn** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.7.10#3]
Crash on server thread from matter overdrive community edition for 1.7, i've never had this crash before using the normal release, crash occured in overworld from rogue android even though i only have -1(nether) whitelisted for androids to spawn in.

Android whitelist doesnt work but blacklist does in both the normal release and community edition

Add a whitelist for dimensions for oregen(currently only blacklist exists)

Config option to remove matter amount from item tooltips (QoL)

**Comment by brandyyn** [comment]
![image](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.7.10/assets/11356565/88977eb7-d7ad-482d-967a-10b1a8834ffd)

i should note that when i use -1 as the whitelist for androids to spawn in the nether, they dont spawn at all, anywhere, not even in the nether and in the community edition i assume they tried to spawn in the overworld as thats where i crashed relating to androids with this whitelist already set

**Comment by infiniteblock** [comment]
https://cdn.discordapp.com/attachments/1209064386950471700/1224159271004934184/MatterOverdrive-1.7.10-0.4.4.jar?ex=661c7a29&is=660a0529&hm=10c9fa14baad1a915cb32702d0037d2b819ed9898361f28f5abec879b827e97f&

Config is broken in first release as they used the modname not modid to save it try this version

**Comment by brandyyn** [comment]
> https://cdn.discordapp.com/attachments/1209064386950471700/1224159271004934184/MatterOverdrive-1.7.10-0.4.4.jar?ex=661c7a29&is=660a0529&hm=10c9fa14baad1a915cb32702d0037d2b819ed9898361f28f5abec879b827e97f&
> 
> Config is broken in first release as they used the modname not modid to save it try this version

But it also applies to the original version

**Comment by brandyyn** [comment]
> https://cdn.discordapp.com/attachments/1209064386950471700/1224159271004934184/MatterOverdrive-1.7.10-0.4.4.jar?ex=661c7a29&is=660a0529&hm=10c9fa14baad1a915cb32702d0037d2b819ed9898361f28f5abec879b827e97f&
> 
> Config is broken in first release as they used the modname not modid to save it try this version

<img width="493" alt="image" src="https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.7.10/assets/11356565/91d7d45b-1047-4a51-91ab-61b6233f8ebb">

**Comment by infiniteblock** [comment]
https://cdn.discordapp.com/attachments/1209064386950471700/1224215524939137075/MatterOverdrive-1.7.10-0.4.4.jar?ex=661cae8d&is=660a398d&hm=01276e5bc807dc19f3ce73c726ef317458d0081249360bcb4b16a9a5c5e1d9f9&

**Comment by brandyyn** [comment]
well i updated and my issues still remain with the original post

**Comment by infiniteblock** [comment]
whitelist is fixed, not sure what the crash is as nothing with that has been changed

**Comment by brandyyn** [comment]
> whitelist is fixed, not sure what the crash is as nothing with that has been changed

just need these

Add a whitelist for dimensions for oregen(currently only blacklist exists)

Config option to remove matter amount from item tooltips (QoL)

**Comment by brandyyn** [comment]
yeah so the whitelist isnt fixed, i just got the chance to test it. 

im trying to have the rogue androids only spawn in the nether, none spawn even though i set the spawn rate to 100

here is my cfg 

![image](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.7.10/assets/11356565/fd5d53c3-eae9-4872-9d8a-1f8b8e136c1e)

**Comment by brandyyn** [comment]
@infiniteblock

**Comment by brandyyn** [comment]
buh
